name: Deploy Marp to Pages
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli

      # 5. 生成 PDF 幻灯片
      - name: Build PDF slides
        run: marp --html *.md
          
      # 8. 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: web