name: Deploy Marp to Pages
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 安装Marp CLI
      - run: npm install -g @marp-team/marp-cli

      # 转换Markdown为HTML
      - run: marp --html *.md

      # 部署到GitHub Pages（使用SSH方式）
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 替换为SSH密钥（需提前生成并配置到GitHub Secrets）
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}  # <button class="citation-flag" data-index="1"><button class="citation-flag" data-index="4"><button class="citation-flag" data-index="7">
          # 指定仓库的SSH地址（格式：git@github.com:<用户名>/<仓库名>.git）
          repository: git@github.com:IcarusSong/my-marp-slides.git  # <button class="citation-flag" data-index="4"><button class="citation-flag" data-index="9">
          # 发布目录（保持与原配置一致）
          publish_dir: ./